# Generated by Django 4.2.17 on 2025-01-29 11:10

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='region',
            field=models.CharField(default='Bordeaux', max_length=200),
        ),
        migrations.AlterField(
            model_name='review',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
