# Generated by Django 4.2.17 on 2025-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='region',
            field=models.CharField(choices=[('Bordeaux', 'Bordeaux'), ('Burgundy', 'Burgundy'), ('Rhône Valley', 'Rhône Valley'), ('Loire Valley', 'Loire Valley'), ('Languedoc-Roussillon', 'Languedoc-Roussillon'), ('Beaujolais', 'Beaujolais'), ('Alsace', 'Alsace'), ('Other', 'Other')], max_length=100),
        ),
    ]
