# Generated by Django 4.2.17 on 2025-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_wine_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='excerpt',
            field=models.TextField(default='wine-name', max_length=100),
        ),
    ]
