# Generated by Django 4.2.17 on 2025-01-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_review_region_alter_review_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='region',
            field=models.CharField(choices=[('southwest', 'Southwest'), ('northwest', 'Northwest'), ('northeast', 'Northeast'), ('southeast', 'Southeast'), ('central', 'Central')], default='southwest', max_length=200),
        ),
    ]
