# Generated by Django 4.2.17 on 2025-02-10 15:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remove_comment_body_comment_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='WineReview',
        ),
    ]
