# Generated by Django 4.2.17 on 2025-01-29 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_review_excerpt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='review',
        ),
    ]
