# Generated by Django 4.2.17 on 2025-02-10 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comment_winereview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
