# Generated by Django 4.2.17 on 2025-02-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_featured_image_comment_rating_comment_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='review',
        ),
    ]
