# Generated by Django 4.2.17 on 2025-02-10 16:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winereview',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='pexels-brettjordan-18687127_v6rpui', max_length=255, verbose_name='image'),
        ),
    ]
