# Generated by Django 4.2.17 on 2025-02-06 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='content',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='pdf_file',
            field=models.FileField(
                default='path/to/default.pdf',
                upload_to='newsletters/',
            ),
        ),
    ]
